Support if allele_string is indel in VEP default input
Ensembl/ensembl-vep pull request #1313
Opened 2022-11-24 14:58 UTC by likhitha-surapaneni

This is a WIP pull request.

The idea is to support indels in VEP default input

2023-01-05 16:16 UTC, dglemos reviewed
In the VCF output, the MINIMISED is not in the header. I think this is why the value 1 (MINIMISED=1 in txt format) is not included in the output.

2023-03-10 11:43 UTC, dglemos commented
To be able to display the original alleles, you could start looking at this method https://github.com/Ensembl/ensembl-vep/blob/release/110/modules/Bio/EnsEMBL/VEP/OutputFactory.pm#L1246 
or here https://github.com/Ensembl/ensembl-vep/blob/release/110/modules/Bio/EnsEMBL/VEP/OutputFactory.pm#L871

2023-03-24 15:20 UTC, dglemos commented
A lot of tests are failing due to 'Original_allele' in the output.

2023-04-28 16:28 UTC, nakib103 requested changes

2023-04-28 16:28 UTC, nakib103 commented on modules/Bio/EnsEMBL/VEP/OutputFactory.pm
> +  my $uploaded_allele_string = $vf->{original_allele_string} || $vf->{allele_string};
`$uploaded_allele_string` is not used elsewhere. a redundant declaration. It would be better to put the logic in L872 directly.

2023-04-28 16:28 UTC, nakib103 commented on modules/Bio/EnsEMBL/VEP/Parser/VEP_input.pm
> +    my $is_in_del = 0;
`$is_indel` will be better for readability.

2023-04-28 16:28 UTC, nakib103 commented on modules/Bio/EnsEMBL/VEP/Parser/VEP_input.pm
> +    $is_in_del = 1 unless $allele_string =~ /[ATGC]{n}\/[ATGC]{n}/ or $allele_string =~ /-/;
I think, the idea here is to discard variant class other than `indel` which would be SNV, substitution, simple insertions and deletions.

`/-/` takes care of the simple insertions and deletions. `/[ATGC]{n}\/[ATGC]{n}/` supposed to take care of SNVs and substitutions . But the problem is, here `n` needs to be a literal integer value. So the regex is not doing anything here (see `3 46358466 46358466 A/C 1` example - it is setting `$is_in_del = 1`)

Unfortunately, we also do not know what this value should be in case of substitution. Splitting the string and making sure the two parts is equal seems the correct approach here.

2023-05-04 12:44 UTC, likhitha-surapaneni commented on modules/Bio/EnsEMBL/VEP/Parser/VEP_input.pm
> +    $is_in_del = 1 unless $allele_string =~ /[ATGC]{n}\/[ATGC]{n}/ or $allele_string =~ /-/;
Hi @nakib103 , the idea is to support insertions or/and deletions and only discard for SNPs or already minimised allele strings

2023-06-02 09:44 UTC, nakib103 approved these changes
Looks good now, thanks for the change!

2023-06-02 09:45 UTC, merged