Fix docker tests
Ensembl/ensembl-vep pull request #1353
Opened 2023-02-10 19:57 UTC by nakib103

- Fix headers added by docker ENV variables
- Add branch to Dockerfile stage 2

2023-02-13 11:28 UTC, nuno-agostinho requested changes

2023-02-13 11:32 UTC, nakib103 commented on docker/Dockerfile
> +ENV BRANCH main
Are you thinking the error could come from having to change the variable name twice? In that case `ARG` will also need changing the branch twice in file, no? 🤔

2023-02-13 17:54 UTC, nakib103 commented on docker/Dockerfile
> +ENV BRANCH main
After discussion it seems more easy to maintain. I have updated `ENV` to `ARG`.

2023-02-15 09:24 UTC, nuno-agostinho approved these changes
Looks great to me, thanks @nakib103!

2023-02-15 09:26 UTC, merged