Docker fix: silent invalid options from ENV and INI config
Ensembl/ensembl-vep pull request #1366
Opened 2023-03-02 15:14 UTC by nuno-agostinho

When running VEP in Docker, we get lots of warnings regarding pre-set environment variables for `INSTALL.pl` that are invalid in VEP:

```bash
$ vep --id rs699 --database --db_version 109 --force
Unknown option: no_update
Ignoring unsupported option 'no_update' found via ENV variable or INI file
Unknown option: no_plugins
Ignoring unsupported option 'no_plugins' found via ENV variable or INI file
Unknown option: pluginsdir
Ignoring unsupported option 'pluginsdir' found via ENV variable or INI file
Unknown option: no_htslib
Ignoring unsupported option 'no_htslib' found via ENV variable or INI file
```

These flags are good to have set up at all times in Docker to abstract users from the internal directory of the Docker image. This PR silently discards invalid options from ENV and INI config file by using the option `pass_through` from GetOpts.

### Testing

Run the following code with and without the changes in this PR:
```
export VEP_VERSION="109.3"
export VEP_JSON=0
vep --id rs699 --database --db_version 109 --force
```

VEP should not print warning messages with these changes.

2023-03-07 09:51 UTC, nakib103 requested changes
Thanks, it is working as intended and removing all warnings. Should we still keep the warning we are giving using `warn`? Because VEP do try to read from ENV variable and it would be better if we have log of what read from there as it is generally hidden (unlike cli/ini params).

In that respect we should also print out the ones we were able to read from the ENV. What is your thought on this?

2023-03-07 11:21 UTC, nuno-agostinho commented
Hey @nakib103,

I think printing environment variables that are ignored just pollutes the log and may mislead users to think something is wrong (such as in the case above with the Docker image). How about if we only print the ignored environment variables with `--verbose`?

Regarding reading from an environment variable, this would have helped avoid some issues in #1357. I would say we could print something like:
```
Setting --database=1 from environment variable VEP_database
Setting --json=1 from environment variable VEP_json
```

Do you think this should this be `--verbose` only or printed at all times?

Thanks for your comments!

2023-03-07 11:32 UTC, nakib103 commented
Yeah, both of them in `--verbose` mode seems logical. They are meant for debugging and I agree having them always pollutes the log.

2023-03-08 16:10 UTC, nuno-agostinho commented
Hey @nakib103, changed the information about reading environment variables to appear when using `--verbose` only.

You can test this by running:
```
export VEP_VERSION="109.3"
export VEP_JSON=0
export VEP_PLUGIN=Downstream
./vep --id rs699 --database --db_version 109 --force --verbose --plugin NMD
```

That should print something like:
```
2023-03-08 16:04:43 - Set 'json=0' from environment variable VEP_JSON
2023-03-08 16:04:43 - Ignored unsupported option 'version=109.3' from environment variable VEP_VERSION
2023-03-08 16:04:43 - Appended 'plugin=Downstream' from environment variable VEP_PLUGIN (full value of plugin: ['NMD', 'Downstream'])
2023-03-08 16:04:43 - Read configuration from environment variables
```

2023-03-09 09:57 UTC, merged