Supporting multiple inputs
Ensembl/ensembl-vep pull request #1389
Opened 2023-03-28 09:33 UTC by likhitha-surapaneni

2023-03-28 14:24 UTC, nuno-agostinho approved these changes
Approved @likhitha-surapaneni's commits! I added some changes, what do you think?

2023-03-28 14:56 UTC, nakib103 requested changes

2023-03-28 14:56 UTC, nakib103 commented on nextflow/workflows/run_vep.nf
> +if( !params.vcf && !params.vcf_dir) {
We can put this inside `workflow{}`. In this way we can call the `workflow vep{}` from other workflow by giving vcf file not through params.

2023-03-28 15:21 UTC, likhitha-surapaneni commented on nextflow/workflows/run_vep.nf
> +if( !params.vcf && !params.vcf_dir) {
Makes sense @nakib103 , will modify accordingly

2023-03-28 15:24 UTC, nuno-agostinho commented on nextflow/workflows/run_vep.nf
> +params.vcf_dir = null
```suggestion
```

2023-03-28 15:31 UTC, nakib103 requested changes

2023-03-28 15:31 UTC, nakib103 commented on nextflow/workflows/run_vep.nf
> +    }
One problem I faced is when I send channel as `vcf` it will error out in file function. One way I solved is to check if `vcf` is string, might be better way to do it - 

```suggestion
    if(vcf instanceof String){
      vcfInput = file(vcf)
      if( !vcfInput.exists() ) {
        exit 1, "The specified VCF input does not exist: ${vcfInput}"
      }

      if (vcfInput.isDirectory()) {
        checkVCF(Channel.fromPath("${vcfInput}/*.gz"))
      } else {
        checkVCF(vcfInput)
      }
    }
    else {
      checkVCF(vcf)
    }
```

2023-03-29 08:31 UTC, nakib103 requested changes

2023-03-29 08:31 UTC, nakib103 commented on nextflow/nf_modules/run_vep.nf
>    cpus params.cpus
is removing the container here is intentional?

2023-03-29 08:55 UTC, nuno-agostinho commented on nextflow/nf_modules/run_vep.nf
>    cpus params.cpus
Yes, @nakib103, we are using labels (`label 'vep'` and `label 'bcftools'`) so it's easy to change the VEP/bcftools version used for all processes in [nextflow.config](https://github.com/likhitha-surapaneni/ensembl-vep/blob/32b01aadbcc9fabdc0ba1d8a12a40ad9ebc613ab/nextflow/nextflow.config#L23-L29)

2023-03-29 09:20 UTC, likhitha-surapaneni reviewed
LGTM

2023-03-29 09:25 UTC, nakib103 approved these changes
Looks good!~ thanks for the great work guys.

2023-03-29 09:34 UTC, merged