bugfix: `overlap` in --custom option with VCF file
Ensembl/ensembl-vep pull request #1410
Opened 2023-05-03 08:40 UTC by nakib103

Reported in https://github.com/Ensembl/ensembl-vep/issues/1405
JIRA - https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5628

The issue is twofold - 
- for multi-allelic variant with SNV and indel we are only considering indel (see [here](https://github.com/Ensembl/ensembl-io/blob/4946a8655e8fdbcf37654c80144a9b09e97604b6/modules/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm#L269))
- for deletion we are getting end co-ordinates with 1 extra bp (see [here](https://github.com/Ensembl/ensembl-io/blob/4946a8655e8fdbcf37654c80144a9b09e97604b6/modules/Bio/EnsEMBL/IO/Parser/BaseVCF4.pm#L322))

But can be solved just by updating the start and end co-ordinates of the parser. 

### Testing
custom VCF file -
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
3	186302389	.	TTA	T	.	.	CLNDISDB=test_1
3	186302392	.	G	T,GTGTGTGTGTGTGTGTGTGTA	.	.	CLNDISDB=test_2
```

Command:
```
vep --id "3:g.186302392G>T" --database --db_version 108 --force --assembly GRCh37  --custom file=<file>,short_name=test,format=vcf,type=overlap,coords=0,fields=CLNDISDB
```

2023-06-16 16:11 UTC, nuno-agostinho requested changes
Hi @nakib103, thanks for the fix. I have some comments about this PR.

2023-06-16 16:11 UTC, nuno-agostinho commented on modules/Bio/EnsEMBL/VEP/AnnotationSource/File/VCF.pm
> +    my $parser_end = $parser_start + length($parser->get_raw_reference) - 1;
Are these two lines the only changes to `_record_overlaps_VF`? Why not fix in that function instead of duplicating code? This fix as is is in conflict with https://github.com/Ensembl/ensembl-vep/pull/1407, but if we fixed in the function, no problem would arise.

2023-06-16 17:19 UTC, nakib103 commented on travisci/harness.sh
> +  if [[ "$COVERALLS" = 'true' && ! "${TRAVIS_PERL_VERSION}" =~ 5.10 ]]; then
This change was made to fix travis build error for coverage. These changes are now already merged through separate PR. I have reverted the change here.

2023-06-16 17:41 UTC, nakib103 commented on modules/Bio/EnsEMBL/VEP/AnnotationSource/File/VCF.pm
> +    my $parser_end = $parser_start + length($parser->get_raw_reference) - 1;
The other function (I assume you are talking about `SUPER::_record_overlaps_VF(@_)`) is a generic function for any parser, so we cannot add this logic here which depends on specifically VCF parser.

I saw you delegated all the new `types` in custom to the `SUPER::_record_overlaps_VF(@_)` function. You need to account that `parser->get_end` can give you one extra bp.

It would be best if we can put this logic in `$parser->get_end` but we need to assess the impact of changing this upstream of a function.

2023-06-19 15:24 UTC, nuno-agostinho approved these changes

2023-06-19 15:59 UTC, merged