bugfix: resolve many-to-one situation in nextflow-vep
Ensembl/ensembl-vep pull request #1448
Opened 2023-06-29 10:44 UTC by nakib103

nextflow-vep many-to-one (and one-to-many) situation with VCF and VEP config file was not working.

This is because giving them as separate channel to `processInputs()` does not work as expected (it is supposed to work like `combine()`). Nextflow handles if one of them is not a channel. 

But going through that route was only considered because of many-to-many situation, and we currently is not supporting that situation I simply used `combine()` which works fine.

Note - also stopped channeling `output_dir` through the workflow, it is used only by the `mergeVCF` step. So we can just give input to that step.

2023-07-03 16:44 UTC, nuno-agostinho requested changes
Hi Nakib, thanks for the PR! I have a comment:

If we use multiple INI config files for a single VCF, we will only have a single VCF file in the end. I put some suggestions on what you can change to avoid this.

See if you agree. Thanks!

2023-07-03 16:44 UTC, nuno-agostinho commented on nextflow/nf_modules/run_vep.nf
> +  tuple val(original_vcf), path(out_vcf), path("${out_vcf}.{tbi,csi}"), val(index_type), emit: files
```suggestion
  tuple val(original_vcf), path(out_vcf), path("${out_vcf}.{tbi,csi}"), path(vep_config), val(index_type), emit: files
```

2023-07-03 16:44 UTC, nuno-agostinho commented on nextflow/nf_modules/merge_VCF.nf
> +  tuple val(original_vcf), path(vcf_files), path(index_files), val(index_type)
```suggestion
  tuple val(original_vcf), path(vcf_files), path(index_files), path(vep_config), val(index_type)
```

2023-07-03 16:44 UTC, nuno-agostinho commented on nextflow/nf_modules/merge_VCF.nf
In line 32, we need to add the name of the VEP config file to distinguish between the results:

```nextflow
  merged_vcf = merged_vcf ?: file(original_vcf).name.replace(".vcf", "_" + file(vep_config).simpleName + "_VEP.vcf")
```

2023-07-04 09:33 UTC, nakib103 commented
Thanks Nuno! I have added the suggestion and fixed one-to-many situation.

2023-07-04 09:42 UTC, nuno-agostinho approved these changes
All is looking fine, @nakib103. Thanks!

2023-07-04 09:50 UTC, merged

2023-07-04 09:55 UTC, nuno-agostinho commented
* Merged to `release/111` and `main`
* Backported to `postreleasefix/110` and `release/110`