nextflow-vep: allow output dir to be a channel
Ensembl/ensembl-vep pull request #1493
Opened 2023-08-31 13:55 UTC by nakib103

2023-09-06 10:01 UTC, nuno-agostinho requested changes

2023-09-06 12:45 UTC, nakib103 commented on nextflow/workflows/run_vep.nf
> +    return Channel.fromPath(toAbsolute(output))
Thanks Nuno! updated.

2023-09-11 09:24 UTC, nuno-agostinho approved these changes
Thanks for the changes, @nakib103!

2023-09-11 09:25 UTC, merged

2023-09-11 09:31 UTC, nuno-agostinho commented
Merged to `main` and `release/111`.