Fix custom annotation of breakends and non-supported SVs (exact mode)
Ensembl/ensembl-vep pull request #1498
Opened 2023-09-14 13:22 UTC by nuno-agostinho

ENSVAR-5610, fixes #1397

- Avoid matching breakpoints with SNPs in exact mode
- Trim whitespaces of warning messages for skipped variants
- Bug fix: avoid skipping all subsequent SVs after skipping one
- Warn when skipping any non-supported SV type

2023-09-20 15:26 UTC, nakib103 requested changes

2023-09-20 15:26 UTC, nakib103 commented on modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm
> -
We should keep this for robustness. Although it generally does not happen for other case than `BND` generally but think of a case like -
`chr11 99819752 test_sv C <INS> 892 PASS SVTYPE=BND;END=99819752`

The parser return `start=99819753` (which obviously is wrong for SV) and does not match the gnomAD SNP, but if we get non-usual case like this -
`chr11 99819751 test_sv C <INS> 892 PASS SVTYPE=BND;END=99819752`

It will match!

2023-09-20 15:26 UTC, nakib103 commented on modules/Bio/EnsEMBL/VEP/AnnotationSource/File/VCF.pm
> +    return 0 if defined $ref_class xor defined $vf_class;
This is redundant with the next check as it makes sure both are defined.
```suggestion
```

2023-09-21 10:40 UTC, nuno-agostinho commented on modules/Bio/EnsEMBL/VEP/Parser.pm
> +  }
Hey Nakib! We only use ensembl-io directly for reading custom annotation: this means we will warn the user about the multiple types of variants that are skipped in custom annotation. Is this information useful by default or just noise?

What about if it's only printed for custom annotation if using `--verbose`? Something like:

```suggestion
  ## unsupported SV types
  if ($self->param('verbose') || $self->isa('Bio::EnsEMBL::VEP::Parser')) {
    Bio::EnsEMBL::VEP::Parser->skipped_variant_msg("$abbrev type is not supported") unless $res;
  }
```

2023-09-21 10:45 UTC, nuno-agostinho commented on modules/Bio/EnsEMBL/VEP/AnnotationSource/File/VCF.pm
> +    return 0 if defined $ref_class xor defined $vf_class;
This is not redundant:
- The other check only returns 0 if both variables are defined and not equal.
- If one is defined but the other is not, then they are not equal, and should also return 0. This check is required for this condition.

2023-09-21 10:48 UTC, nuno-agostinho commented on modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm
> -
Hey Nakib, I simply moved this from `File.pm` to `File/VCF.pm` because this can only be done for custom VCF files (other custom annotation formats do not have variant type, so we cannot match based on it). The code is now applied to VCF annotation only.

2023-09-21 12:52 UTC, nakib103 requested changes

2023-09-21 12:52 UTC, nakib103 commented on modules/Bio/EnsEMBL/VEP/AnnotationSource/File/VCF.pm
> +    return 0 if defined $ref_class xor defined $vf_class;
ah, sorry - I missed that it was an `if`, you can modify the next condition to have unless - 

`return 0 unless defined $ref_class && defined $vf_class && $ref_class eq $vf_class`;

the condition can only be true if both are defined and equal.

2023-09-21 12:52 UTC, nakib103 commented on modules/Bio/EnsEMBL/VEP/AnnotationSource/File.pm
> -
That makes sense!

2023-09-28 16:50 UTC, nakib103 approved these changes
LOTM !~

2023-09-29 09:26 UTC, merged