Remove redundant symbolic alt to so term hash
Ensembl/ensembl-vep pull request #1643
Opened 2024-03-21 11:30 UTC by nakib103

See https://github.com/Ensembl/ensembl-variation/pull/1075

2024-08-21 13:15 UTC, nakib103 commented
@nuno-agostinho, 
The unit test on [one before the last](https://github.com/Ensembl/ensembl-vep/pull/1643/commits/ca84f83d6283d573012cb3b1daf5f0543470396e) take accounts the change in ensembl-variation and passed. You can ignore the unit test failure in the last commit.

2024-09-06 12:24 UTC, nuno-agostinho requested changes
Same concern as expressed in https://github.com/Ensembl/ensembl-variation/pull/1075#pullrequestreview-2286025167.

Otherwise, I just have small suggestions.

2024-09-26 12:22 UTC, nakib103 commented on modules/Bio/EnsEMBL/VEP/Parser.pm
> +    &_valid_region_regex
it is used in - 
- https://github.com/Ensembl/ensembl-vep/blob/31a3581b84495b617b2f3980da6c6313ca6d238f/modules/Bio/EnsEMBL/VEP/Parser/Region.pm#L171 which is a child class so no need of import.
- `check_format` for `ensembl-variation`. We need to import for that. I am just giving preference to remove redundancy.

2024-12-06 16:17 UTC, nakib103 commented
Closing this PR and will create a new one.

2024-12-06 16:17 UTC, closed without merging