Nextflow: Accept and split non-VCF input formats
Ensembl/ensembl-vep pull request #1675
Opened 2024-05-17 13:09 UTC by nuno-agostinho

This PR improves the Nextlow pipeline to run VEP on non-VCF files.

## Changelog

* Replace argument `--vcf` with `--input`
    - 8d2b87c50: `--vcf` still supported for backwards compatibility (now prints deprecated message)
* When giving (a folder with) input data to run VEP on:
    - Ignore files with specific extensions: `ini`, `registry`, `tbi`, `csi`
    - If `vcf` or `vcf.gz` extension, parse using `checkVCF`, `generateSplits` and `splitVCF` (as previously) before running VEP
    - If any other extensions, split input files with `splitText` based on `params.bin_size` before running VEP
* In the end, merge split files (as previously)
* 37e4e5b2f: New option `--sort` to sort VCF input/output from VEP (disabled by default)
* 388339075: Remove mentions to deprecated `--skip_check`
* Update documentation

## Testing

Running the pipeline with different input files ([input.tar.gz](https://github.com/Ensembl/ensembl-vep/files/15349622/input.tar.gz)):

```
nextflow run ${ENSEMBL_ROOT_DIR}/ensembl-vep/nextflow/workflows/run_vep.nf \
  -profile slurm \
  -resume \
  --input input \
  --outdir outdir \
  --vep_config vep_config.ini
```

2024-05-21 15:50 UTC, nakib103 requested changes
@nuno-agostinho , thanks everything works as expected.
I have some minor change requests

2024-05-22 10:32 UTC, nuno-agostinho commented on nextflow/README.md
> +  --input FILE              Input file: if VCF, it must be sorted and bgzipped. Alternatively, can also be a directory containing input files
[05a128e](https://github.com/Ensembl/ensembl-vep/pull/1675/commits/05a128e478e943448e277e4d10bfc5ae05acc037): Updated so that input VCF file is sorted when using `--sort`

2024-05-22 10:34 UTC, nuno-agostinho commented on nextflow/nf_modules/merge_VCF.nf
> +  tuple val(meta), val(original), path(vcf_files), path(index_files), val(vep_config)
Fixed.

2024-05-22 12:50 UTC, nakib103 requested changes

2024-05-22 13:30 UTC, nuno-agostinho commented on nextflow/README.md
> +  --input FILE              Input file (if unsorted, use --sort to avoid errors). Alternatively, can also be a directory containing input files
I can sort the final VCF output (before bgzip + tabix) to avoid any sorting issues, wouldn't that be a better solution?

2024-05-22 13:52 UTC, nakib103 commented on nextflow/README.md
> +  --input FILE              Input file (if unsorted, use --sort to avoid errors). Alternatively, can also be a directory containing input files
If there are 100 variants unordered (with the distance between the unordered variant > `100bp`) it would not give error ([here](https://github.com/Ensembl/ensembl-vep/blob/31a3581b84495b617b2f3980da6c6313ca6d238f/modules/Bio/EnsEMBL/VEP/Constants.pm#L342-L343)). This error occurs while running vep and does not matter if we are sorting the output.

The sorting here is only avoiding error in the tabixing of the output file. We might make it clear with something like this -
```suggestion
  --input FILE              Input file (if unsorted, use --sort to avoid errors in indexing the output file). Alternatively, can also be a directory containing input files
```

2024-05-29 08:16 UTC, nuno-agostinho commented on nextflow/README.md
> +  --input FILE              Input file (if unsorted, use --sort to avoid errors). Alternatively, can also be a directory containing input files
Thanks, Nakib! Fixed based on your suggestion.

2024-06-03 08:48 UTC, nakib103 approved these changes
Looks good!~ thanks @nuno-agostinho

2024-06-03 08:48 UTC, merged