Nextflow VEP: support Seqera platform
Ensembl/ensembl-vep pull request #1724
Opened 2024-07-17 13:23 UTC by nuno-agostinho

Changes to organisation of Nextflow VEP files in order to support Seqera platform

2024-08-05 08:58 UTC, veidenberg commented on nextflow/nextflow.config
> +    conda.enabled          = true
Just checking, can VEP bypass Anaconda?

2024-08-05 15:21 UTC, nakib103 requested changes

2024-08-05 15:21 UTC, nakib103 commented on nextflow/workflows/run_vep.nf
> +          ( it.file =~ '\\.vcf$' && it.file.readLines()[0][0] =~ '^#' ) ||
@nuno-agostinho,

To run a VCF file through the `runVEPonVCF` we should ensure the file have both fileformat and the header line -
```
##fileformat=VCFv4.2
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
```

Can we check if both of these lines are present?

2024-08-05 17:56 UTC, nuno-agostinho commented on nextflow/workflows/run_vep.nf
> +          ( it.file =~ '\\.vcf$' && it.file.readLines()[0][0] =~ '^#' ) ||
Thanks for the suggestion! Included in new commit: https://github.com/Ensembl/ensembl-vep/pull/1724/commits/b8d44e974caa81a2538b2002b82df789a2485908

2024-08-07 13:24 UTC, nakib103 approved these changes
Looks good!~

2024-08-07 13:29 UTC, merged