Capture uploaded allele correctly for VCF input
Ensembl/ensembl-vep pull request #1744
Opened 2024-08-20 10:50 UTC by likhitha-surapaneni

Ticket: [ENSVAR-5858](https://www.ebi.ac.uk/panda/jira/browse/ENSVAR-5858)

2024-08-21 13:07 UTC, likhitha-surapaneni commented on modules/Bio/EnsEMBL/VEP/Parser.pm
> +        $new_vf->{original_allele_string} = $vf->{original_allele_string} || $vf->{allele_string};
Can we assign `$vf->{original_allele_string}` only if VCF?

2024-08-22 10:51 UTC, nakib103 requested changes

2024-08-22 10:51 UTC, nakib103 commented on modules/Bio/EnsEMBL/VEP/Parser.pm
> +        $new_vf->{original_allele_string} = $vf->{original_allele_string} || $vf->{allele_string};
The way you are doing should be okay. For other parsers `$vf->{original_allele_string}` is not defined so it will take the value from `$vf->{allele_string}`. 

To only assign only if VCF we can check the parser type is `Bio::EnsEMBL::VEP::Parser::VCF` but seems redundant.

2024-08-22 10:51 UTC, nakib103 commented on modules/Bio/EnsEMBL/VEP/Parser.pm
I think there is an error in L859 where we determine the `$is_indel`. 

Say for a VCF input `1 100 . A AG` the `$ref_allele_string` and `$alt_allele_string` will be `-\G` and thus length is same. Maybe we should have a check if `$ref_allele_string` or `$ref_allele_string` have `-`.

2024-08-22 11:02 UTC, nakib103 requested changes

2024-08-22 11:02 UTC, nakib103 commented on modules/Bio/EnsEMBL/VEP/Parser.pm
> +      $vf->{minimised} = 1;
```suggestion
      push @return, $vf;
      $vf->{minimised} = 1;
```

Also need to return the $vf otherwise you get undef and empty results.

2024-08-22 11:19 UTC, likhitha-surapaneni commented on modules/Bio/EnsEMBL/VEP/Parser.pm
Hi @nakib103 ,
We are checking if the allele_string contains `-` [here](https://github.com/Ensembl/ensembl-vep/blob/bf0d2cf9e9d12a6512a15805e712554760793036/modules/Bio/EnsEMBL/VEP/Parser.pm#L859), are you referring to an additional check?

2024-08-22 11:26 UTC, nakib103 commented on modules/Bio/EnsEMBL/VEP/Parser.pm
Ah, right. You are already checking it. I think it is the condition that needs to change -
The `or` just needs to be changed to `and` and the `=~` needs to change to `!~`.

2024-08-22 11:34 UTC, likhitha-surapaneni commented on modules/Bio/EnsEMBL/VEP/Parser.pm
We also do not want to call minimise_alleles if it is already minimised such as the case in `-/G`, maybe the variable name can be changed to `is_non_minimised_indel` or do you think there is any case we might be missing?

2024-08-22 11:42 UTC, nakib103 commented on modules/Bio/EnsEMBL/VEP/Parser.pm
True, we do not need to pass the `-/G` through minimisation. Changing the variable name might make it clearer. I was evaluating the condition to check for indels.
thanks @likhitha-surapaneni

2024-12-06 18:17 UTC, nakib103 commented on modules/Bio/EnsEMBL/VEP/Parser.pm
> +        if (length($ref_allele_string) != length($alt) or $original_allele_string =~ /^-/){
what happens to `G/-/GGG` variant?
also `-/G`?

first should not go to minimise - should not be a problem
second one would not go to minimise - nothing would be done. so worthless.

2024-12-09 08:24 UTC, nakib103 requested changes

2024-12-10 13:53 UTC, likhitha-surapaneni commented on modules/Bio/EnsEMBL/VEP/OutputFactory.pm
> +    if(defined($vf->{first})) {
The way rejoin_required works is, 
it relies on a first variant_allele object which acts as an anchor for the variant and joins all the subsequent variant alleles to the anchor object. The proxy for first/anchor variant previously used to be $vf->{original_allele_string}. However with this[ line](https://github.com/Ensembl/ensembl-vep/blob/56d965a6dd5bf23205c17ae10639a40434f9d322/modules/Bio/EnsEMBL/VEP/Parser.pm#L860) , original_allele_string is defined for all variant alleles. We need another proxy variable for first variant, hence defined [$vf->{first}](https://github.com/Ensembl/ensembl-vep/blob/56d965a6dd5bf23205c17ae10639a40434f9d322/modules/Bio/EnsEMBL/VEP/InputBuffer.pm#L667)

2024-12-10 13:59 UTC, likhitha-surapaneni commented on modules/Bio/EnsEMBL/VEP/Parser.pm
> +        if (length($ref_allele_string) != length($alt) or $original_allele_string =~ /^-/){
[$original_allele_string](https://github.com/Ensembl/ensembl-vep/blob/56d965a6dd5bf23205c17ae10639a40434f9d322/modules/Bio/EnsEMBL/VEP/Parser.pm#L860) contains both ref_allele and alt_alleles in the same string separated by "/"

2024-12-11 14:52 UTC, nakib103 commented on modules/Bio/EnsEMBL/VEP/Parser.pm
> +        if (length($ref_allele_string) != length($alt) or $original_allele_string =~ /^-/){
true, but with `^` you are only checking `-` allele for ref and missing deletions?

2025-01-30 09:39 UTC, likhitha-surapaneni commented on modules/Bio/EnsEMBL/VEP/Parser.pm
> +      $vf->{minimised} = 1;
Hi @nakib103 , can you please test this example with the latest commit. The allele is expected to be similar to when running `--minimal`

2025-01-31 14:39 UTC, dglemos commented
The `MINIMISED` is missing from the header, so in the VCF output even when the variant is minimised this info is not in the file. The only outputs with this info are the default and json.

2025-01-31 14:55 UTC, dglemos commented
When the input is in VCF format, example:
`1       961320  .       G       GCAGGCTCGGCC    .       .       .`

In the vep default output, the `Uploaded_variation` is represented with minimised alleles: 
`1_961321_-/CAGGCTCGGCC `
In this scenario matching the alleles is more difficult.

2025-02-04 08:27 UTC, dglemos commented
Yes, UPLOADED_ALLELE is enough to match the alleles. It should be returned by default though, if the variant is minimised it should return the original alleles too.

2025-02-04 09:06 UTC, nakib103 commented
> Yes, UPLOADED_ALLELE is enough to match the alleles. It should be returned by default though, if the variant is minimised it should return the original alleles too.

I think it is generally advisable to not update the default output list so not to break existing pipelines.

2025-02-04 09:48 UTC, likhitha-surapaneni commented on modules/Bio/EnsEMBL/VEP/Parser.pm
> +      $vf->{minimised} = 1;
Hi @nakib103 , the output is still minimsed if you notice the 3rd column (correct me if I got it wrong). We have the allele "-" as the minimised representation for first alternative allele is GG/- and for the second one is G/-. The problem however is that there is no way to differentiate between the alternative alleles as both show "-" which is also a existing problem with the option `minimal` and needs to be addressed probably in a future ticket. Let me know if this makes sense

2025-02-04 10:18 UTC, nakib103 commented on modules/Bio/EnsEMBL/VEP/Parser.pm
> +      $vf->{minimised} = 1;
I was actually looking at the `Uploaded_variation` column, it does not seem to be minimised as it does for bi-allelic variants (see - `1 961320 961324 GCAGG/GCA +`).

But the `Allele` column shows the alleles are minimised. It seems Uploaded_variation string has different logic, should we address this?

2025-02-04 10:26 UTC, likhitha-surapaneni commented on modules/Bio/EnsEMBL/VEP/Parser.pm
> +      $vf->{minimised} = 1;
Yes, I agree @nakib103. The uploaded variation was not expected to minimise alleles but it was minimising the alleles in some cases due to the way we populate the column and previously it was difficult to correct this as it is also the default option, hence the approach was taken to capture original allele with a different flag (`--uploaded_allele`). However, I agree it may also be worth investigating why uploaded variation is minimising the allele in some cases and not doing it in other cases.

2025-03-04 13:59 UTC, likhitha-surapaneni commented
> The `MINIMISED` is missing from the header, so in the VCF output even when the variant is minimised this info is not in the file. The only outputs with this info are the default and json.

Currently, the header is formed and written to the output file before looking at the input: https://github.com/Ensembl/ensembl-vep/blob/a6786e4357f442a81624f58d9e79f343909d717f/modules/Bio/EnsEMBL/VEP/Runner.pm#L204-L209

2025-03-07 10:22 UTC, nakib103 approved these changes
Looks good!~

2025-04-25 13:19 UTC, dglemos approved these changes
@likhitha-surapaneni, the changes look good.

2025-04-25 13:22 UTC, merged