Add new option to fetch clinvar somatic classification
Ensembl/ensembl-vep pull request #1794
Opened 2024-11-18 15:15 UTC by dglemos

Add option to return new clinvar somatic classification.

- [ ] update dump pipeline
- [ ] add option to vep
- [ ] output factory to return new data types
- [ ] patch test db
- [ ] fix and add tests

2024-11-21 13:05 UTC, dglemos commented
Tests fail because of missing method `get_somatic_clin_impact_by_location`. This is part of this PR https://github.com/Ensembl/ensembl-variation/pull/1117

2025-01-13 09:33 UTC, nakib103 requested changes

2025-01-27 12:49 UTC, nakib103 commented on t/test-genome-DBs/homo_vepiens/variation/table.sql
> +  `DNA_type` enum('Germline','Somatic') DEFAULT NULL,
This was an old unpublished comment.

2025-01-31 09:35 UTC, nakib103 approved these changes
LGTM!~

2025-02-13 15:45 UTC, jamie-m-a approved these changes
Works - thanks @dglemos

2025-02-13 15:45 UTC, merged