Variant Recoder report variant synonyms
Ensembl/ensembl-vep pull request #934
Opened 2021-02-17 12:54 UTC by dglemos

ENSVAR-2692
Dependent on https://github.com/Ensembl/ensembl-variation/pull/699

2021-03-22 15:50 UTC, aparton requested changes

2021-03-22 15:50 UTC, aparton commented on modules/Bio/EnsEMBL/VEP/OutputFactory.pm
> +    variant_synonyms
Should we use the current `var_synonyms` instead of adding a new output field?

2021-03-22 15:50 UTC, aparton commented on modules/Bio/EnsEMBL/VEP/OutputFactory.pm
> +  if($self->{variant_synonyms} || (defined($self->{_config}->{_params}->{fields}) && grep(/variant_synonyms/, @{$self->{_config}->{_params}->{fields}}))){
Switching parameters on with fields can get us into some problems and lead to duplication of data within VEP, for example:
perl vep -id rs699 --cache --dir $CACHE_DIR --var_synonyms --fields var_synonyms,variant_synonyms

2021-03-25 13:01 UTC, dglemos commented
@aparton I deleted the new flag `variant_synonyms`. Both Variant Recoder and VEP use `var_synonyms`.
$0 is used to check which tool is running - in the tests Variant Recoder is 't/VariantRecoder.t' while the tool is 'variant_recoder', that is why there are two checks `$0 =~ /variant_recoder/ || $0 =~ /VariantRecoder/`

2021-03-25 16:48 UTC, dglemos commented
@aparton I added flag `is_vr` to VariantRecoder.pm. Later we can use this flag to check which tool is running. 
It works on Web, here is a sandbox to test: http://ves-hx2-76.ebi.ac.uk:7040/info/docs/tools/vep/index.html

2021-04-06 16:43 UTC, aparton requested changes

2021-04-06 16:43 UTC, aparton commented on modules/Bio/EnsEMBL/VEP/OutputFactory.pm
> +  if($self->{_config}->{_params}->{is_vr} && ($self->{var_synonyms} || (defined($self->{_config}->{_params}->{fields}) && grep(/var_synonyms/, @{$self->{_config}->{_params}->{fields}})))){
Do we need the `(defined($self->{_config}->{_params}->{fields}) && grep(/var_synonyms/, @{$self->{_config}->{_params}->{fields}}` section? Using --fields to switch parameters on can lead to issues if we ever require code to be run before we reach the OutputFactory

2021-04-07 16:52 UTC, dglemos commented on modules/Bio/EnsEMBL/VEP/OutputFactory.pm
> +  if($self->{_config}->{_params}->{is_vr} && ($self->{var_synonyms} || (defined($self->{_config}->{_params}->{fields}) && grep(/var_synonyms/, @{$self->{_config}->{_params}->{fields}})))){
Deleted the block of code. `fields` doesn't switch the option on anymore.

2021-05-13 11:00 UTC, merged